apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secrets
    namespace: elastic
stringData:
    ELASTICSEARCH_USER: ENC[AES256_GCM,data:ab7TexsDmw==,iv:aBYC+EhLXLT3ol2uTThvtSmRkMBKy05t+mYgPaGlTt0=,tag:1jw2nyVgD4aLkdnNg2sA4g==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:3BQU9OKaktKCO0tEoMVeEwWx48LohJrf,iv:AzBbtP/UUBWde98nQFtMXp+mokXLvOiry8PoT0oC920=,tag:ZhWrdx2eoR8ffZmoVjr5DQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Q1oya2x1bmpaOHBVaVBK
            TmdyNEdmVGlOZ1I1RTFMeTVra1creGNSOWlrCmh4VzBFNmhSb3lnc0NsU1R4R2xz
            VHN0bE44NGZQMnFxakdWMXNkMXVSdUkKLS0tIE9UcFB6TkJaQVlzWWZ2M2Z4WmJN
            c3ZvNEo4THhVSVE2UmJzKzFQZGlyaTAKan2eba+RsrR7mEIjSTISgT2jS9C+nQGA
            uoQ2TVaEIFquTm35aGWfN8eGeQnzUuuM+sCCzZU0S78AsGVDt1T3NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T07:45:10Z"
    mac: ENC[AES256_GCM,data:0ca9Y261FTnrsbWuSt6Lmw8Dwv9IS8kd+tYFwNsnAHHIjC1tK15yb8/7pYFjQT1VxyP5vIr0BT4bNtBkdsrtW4CfZqnIKlgeFDjPMDaqLPQXld9NFgUry1N8uuJvxB/JRFkaYVd+D5raZSvizJIki2WfaZ4cBaT1OBCn/B9Iy10=,iv:vgMo67AnucgbPIQxABGCVg63xFVegDhBpoYTQyHxKm4=,tag:QGD8hh8rHxYyT8Ou5vuyLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secrets
    namespace: fluentd-system
stringData:
    ELASTICSEARCH_USER: ENC[AES256_GCM,data:UxI5Wcpa5A==,iv:Xk27DKCoFphb6Sx7tLWfQOLGoPNfHWavG2NPPOvNV7k=,tag:p4vzqfOLda5vDCqCtqzQZg==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:VlxRk+9mxJym2MOmiFPugMY/pHKB0Qmf,iv:OLN6yshWeGUEFOE17gN3ti4Zq0LdiWuSmzNBXxxUmOU=,tag:ixJfN6DUYYFPGq1f3qiv0Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Q1oya2x1bmpaOHBVaVBK
            TmdyNEdmVGlOZ1I1RTFMeTVra1creGNSOWlrCmh4VzBFNmhSb3lnc0NsU1R4R2xz
            VHN0bE44NGZQMnFxakdWMXNkMXVSdUkKLS0tIE9UcFB6TkJaQVlzWWZ2M2Z4WmJN
            c3ZvNEo4THhVSVE2UmJzKzFQZGlyaTAKan2eba+RsrR7mEIjSTISgT2jS9C+nQGA
            uoQ2TVaEIFquTm35aGWfN8eGeQnzUuuM+sCCzZU0S78AsGVDt1T3NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T07:45:10Z"
    mac: ENC[AES256_GCM,data:0ca9Y261FTnrsbWuSt6Lmw8Dwv9IS8kd+tYFwNsnAHHIjC1tK15yb8/7pYFjQT1VxyP5vIr0BT4bNtBkdsrtW4CfZqnIKlgeFDjPMDaqLPQXld9NFgUry1N8uuJvxB/JRFkaYVd+D5raZSvizJIki2WfaZ4cBaT1OBCn/B9Iy10=,iv:vgMo67AnucgbPIQxABGCVg63xFVegDhBpoYTQyHxKm4=,tag:QGD8hh8rHxYyT8Ou5vuyLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
