apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-setup-logs-data-stream-role-secrets
    namespace: elastic
stringData:
    roles.yml: ENC[AES256_GCM,data:oTGNBlEVH2L/1MTz0OJMQGV/eCESNbGCRlD7bKleN8S9j8BbTQB5PFVFQ1PSq6W3RJJcwX0C8PoM9/mpwSe3442raipIfOcHxFLt1rZseSLpPM7i3QIbZ5uQsjplHtDvvbETmKgMOU+HDz7hVsV1wzv1R6tmLevIbL5rBVyvfx5d53ATOC0qXQcxjmSoXcp0D4tVAcrqYmu1+57XPcDq5WP/1MopkYXnLk8GBmxUVw4BWynT83goKcyIrjemkAk8rXAIMCVLlHSHzXkbUE5FeOXnznv98LB39ujypzoQ+9UDhA0SkkGy+iSLcuzRlFN+EOWrWFW5I85ELCBIFPPuLVld3kl7ie/9IiaYgHiXGtx3XtKESILp1JT01eB7oyBlydnsHBbeC5GdiZZaIoOeEtxrV4QeV2vi+18UkYjUxUIgc4NolSvyspNz7Xwp/c2s6g6EGvzC4GO+,iv:XoEwlG/9wljwRYgnWS3ekvCXizWsA1CFeotg6hXurRc=,tag:nFq7sG/SYhj5ky20T9CXWg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWE2N1JqU1hLbHRxTy9W
            elNabVJ1L3RSWjBzRGZwV0h1WGVTTUEvVkc0ClJDZnFrT0NQOUJOVUMvTkNxcThx
            SzB2UkFpTnNBbi9iVUxTdVRpaFJlRFEKLS0tIHBBUjlHTEtLS2xRcjBtVmNaTlhU
            dkpZZ0JrVnFuazhIZ25XMStORlUyQm8Ku81SO5hVyeWh1zGlryH3GmJABa1xmlIJ
            F/x4dv29/xjX7pjqOZ3ilcNjsKUwuL1Qd/X/As83S6bkG4/uoZ7S2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T07:29:22Z"
    mac: ENC[AES256_GCM,data:lln4A10oRbiR2jvIqEcwcY+InsmBt7Ej6z/t7OZ4pfi/rAtoGXfFzDZOOcwOmW9Vb3jXhw/E2cI8C8xbl7bGnGL0waTwDBA9Csq9iPT5ehBZuYJCzptzhcThorxtX6BBQzbgeHWovFEwaxTuMsCeLurqBx78+6jvuA8gvGI9jBs=,iv:3x0RwENAn1Ho9xzkexaeYT9nru+vWBu6owIWSVwfysM=,tag:/P+rGCRFwb4HpTfDaUcEhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-role-secrets
    namespace: elastic
stringData:
    roles.yml: ENC[AES256_GCM,data:9UWlMVrkcJqb0JTaxPumxnm2N4LMfrT+lHj/oMDOwElhFbc61tXErXVroPxFYlI3+Kp0hDJjqWKyDAEyWzLkRPkyAxneQ+QbdyIr7SuoSlR84+ewepWuIfKdeXU43l/6A6BujTFHotBV87P+6BW0VWrh3YkpwLlIVssLiYHNY+SoxxMBBfD5RxHe+JpL7IhHJrY6sju0ynncmFNkSVvdPXdeKwG0IA==,iv:EjWEMzR4Dvyr5LKk/ZJEh7TbDkWQMSRsYVsPqGVdTn8=,tag:mxl2Dmwqmm2iN0xEV9BrWg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWE2N1JqU1hLbHRxTy9W
            elNabVJ1L3RSWjBzRGZwV0h1WGVTTUEvVkc0ClJDZnFrT0NQOUJOVUMvTkNxcThx
            SzB2UkFpTnNBbi9iVUxTdVRpaFJlRFEKLS0tIHBBUjlHTEtLS2xRcjBtVmNaTlhU
            dkpZZ0JrVnFuazhIZ25XMStORlUyQm8Ku81SO5hVyeWh1zGlryH3GmJABa1xmlIJ
            F/x4dv29/xjX7pjqOZ3ilcNjsKUwuL1Qd/X/As83S6bkG4/uoZ7S2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T07:29:22Z"
    mac: ENC[AES256_GCM,data:lln4A10oRbiR2jvIqEcwcY+InsmBt7Ej6z/t7OZ4pfi/rAtoGXfFzDZOOcwOmW9Vb3jXhw/E2cI8C8xbl7bGnGL0waTwDBA9Csq9iPT5ehBZuYJCzptzhcThorxtX6BBQzbgeHWovFEwaxTuMsCeLurqBx78+6jvuA8gvGI9jBs=,iv:3x0RwENAn1Ho9xzkexaeYT9nru+vWBu6owIWSVwfysM=,tag:/P+rGCRFwb4HpTfDaUcEhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-elastic-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:bTGfaq/swg==,iv:hVkMOoFpw9+W0jza1+izw4EoQ4rBJoxDjkp/TpfSd+w=,tag:Scntvy5Upu/EeJtspjitHg==,type:str]
    password: ENC[AES256_GCM,data:0bHgAm6kgrbhRriAtaPjY45lWtyisM9h,iv:AGTGBg5WvBVCuvpTxYJqKF9QzinIdRBPzf5ZjDViir8=,tag:EzqQMrTAqaKIL5y7qcmDxQ==,type:str]
    roles: ENC[AES256_GCM,data:ieM3mNntUzvY,iv:8rZCsWWu0mZK7jt/wj7iKmrTQ1cnLpgaAmmkfZWTvIY=,tag:b99ZIDG1OoISvj5giGTWlw==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWE2N1JqU1hLbHRxTy9W
            elNabVJ1L3RSWjBzRGZwV0h1WGVTTUEvVkc0ClJDZnFrT0NQOUJOVUMvTkNxcThx
            SzB2UkFpTnNBbi9iVUxTdVRpaFJlRFEKLS0tIHBBUjlHTEtLS2xRcjBtVmNaTlhU
            dkpZZ0JrVnFuazhIZ25XMStORlUyQm8Ku81SO5hVyeWh1zGlryH3GmJABa1xmlIJ
            F/x4dv29/xjX7pjqOZ3ilcNjsKUwuL1Qd/X/As83S6bkG4/uoZ7S2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T07:29:22Z"
    mac: ENC[AES256_GCM,data:lln4A10oRbiR2jvIqEcwcY+InsmBt7Ej6z/t7OZ4pfi/rAtoGXfFzDZOOcwOmW9Vb3jXhw/E2cI8C8xbl7bGnGL0waTwDBA9Csq9iPT5ehBZuYJCzptzhcThorxtX6BBQzbgeHWovFEwaxTuMsCeLurqBx78+6jvuA8gvGI9jBs=,iv:3x0RwENAn1Ho9xzkexaeYT9nru+vWBu6owIWSVwfysM=,tag:/P+rGCRFwb4HpTfDaUcEhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-setup-logs-data-stream-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:UfFV/Ayprj3jipmHZV4rXMlQmQrCbQ==,iv:uT+IftuklVP2qoqSLUYR8NuDm+DXsOAvae/rhh/cz74=,tag:/+fq7NTI+OrV0AzaHWvxJg==,type:str]
    password: ENC[AES256_GCM,data:pKznlsLR4GNbU8cZoHmOO+7bavYCYFwo,iv:WpiPOnQhHdNNoanqkQx3qu8O67IEtwY/ujxyB778fvM=,tag:EMulWBY9fAjNtSMjW3CYWw==,type:str]
    roles: ENC[AES256_GCM,data:TwrJsMgWbz9V3IRgXaBhkXfYapUoTw==,iv:rUuqEygowqNu+msZu9qlgoz6LAP7eR4yeR3AHI5/S9U=,tag:+Z9bKdMq1pjLqCwprnOnuw==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWE2N1JqU1hLbHRxTy9W
            elNabVJ1L3RSWjBzRGZwV0h1WGVTTUEvVkc0ClJDZnFrT0NQOUJOVUMvTkNxcThx
            SzB2UkFpTnNBbi9iVUxTdVRpaFJlRFEKLS0tIHBBUjlHTEtLS2xRcjBtVmNaTlhU
            dkpZZ0JrVnFuazhIZ25XMStORlUyQm8Ku81SO5hVyeWh1zGlryH3GmJABa1xmlIJ
            F/x4dv29/xjX7pjqOZ3ilcNjsKUwuL1Qd/X/As83S6bkG4/uoZ7S2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T07:29:22Z"
    mac: ENC[AES256_GCM,data:lln4A10oRbiR2jvIqEcwcY+InsmBt7Ej6z/t7OZ4pfi/rAtoGXfFzDZOOcwOmW9Vb3jXhw/E2cI8C8xbl7bGnGL0waTwDBA9Csq9iPT5ehBZuYJCzptzhcThorxtX6BBQzbgeHWovFEwaxTuMsCeLurqBx78+6jvuA8gvGI9jBs=,iv:3x0RwENAn1Ho9xzkexaeYT9nru+vWBu6owIWSVwfysM=,tag:/P+rGCRFwb4HpTfDaUcEhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:1xIILAyD0FHm95c=,iv:TnJ5v+H/zHijkItACalIs/1VpfTupVRM9zL+XHvkisk=,tag:dz+Jn2eQ8h6ZPs+rRxMWKQ==,type:str]
    password: ENC[AES256_GCM,data:30E9uA15U7ZcOef2RFN+qXr0BPlqoYe0,iv:cpcVWvCgpHZsJxJ79TK9+QidhQ264qvOuyI28xrA8Bk=,tag:uVYaHmOmwWB+EPn/A28r+w==,type:str]
    roles: ENC[AES256_GCM,data:OR6HunFu0K937pE=,iv:X+QiR/RWIgRE0ldA9zQQpDV4JN+z+WoaLRZDSuTz1Dg=,tag:bxtmmCsGdsFwguE/uLOguw==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWE2N1JqU1hLbHRxTy9W
            elNabVJ1L3RSWjBzRGZwV0h1WGVTTUEvVkc0ClJDZnFrT0NQOUJOVUMvTkNxcThx
            SzB2UkFpTnNBbi9iVUxTdVRpaFJlRFEKLS0tIHBBUjlHTEtLS2xRcjBtVmNaTlhU
            dkpZZ0JrVnFuazhIZ25XMStORlUyQm8Ku81SO5hVyeWh1zGlryH3GmJABa1xmlIJ
            F/x4dv29/xjX7pjqOZ3ilcNjsKUwuL1Qd/X/As83S6bkG4/uoZ7S2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T07:29:22Z"
    mac: ENC[AES256_GCM,data:lln4A10oRbiR2jvIqEcwcY+InsmBt7Ej6z/t7OZ4pfi/rAtoGXfFzDZOOcwOmW9Vb3jXhw/E2cI8C8xbl7bGnGL0waTwDBA9Csq9iPT5ehBZuYJCzptzhcThorxtX6BBQzbgeHWovFEwaxTuMsCeLurqBx78+6jvuA8gvGI9jBs=,iv:3x0RwENAn1Ho9xzkexaeYT9nru+vWBu6owIWSVwfysM=,tag:/P+rGCRFwb4HpTfDaUcEhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secrets
    namespace: fluentd-system
stringData:
    ELASTICSEARCH_USER: ENC[AES256_GCM,data:hC1NHOczMepSx80=,iv:6/tqkoAp5gjRg69dM8xRHqt0oK8rI55V9XGJUcGIwSo=,tag:YSHNsundG5i7SSF9wCYx/w==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:zJ6PnZ/0vBLCCxVyjcTxYeu3K6I4wQh+,iv:pDKA2U9LduVl0LnOL3eP6ei6fau4NuKYslezIVuRvNY=,tag:yS2C45glOdKOuOg0Nr4Naw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OWE2N1JqU1hLbHRxTy9W
            elNabVJ1L3RSWjBzRGZwV0h1WGVTTUEvVkc0ClJDZnFrT0NQOUJOVUMvTkNxcThx
            SzB2UkFpTnNBbi9iVUxTdVRpaFJlRFEKLS0tIHBBUjlHTEtLS2xRcjBtVmNaTlhU
            dkpZZ0JrVnFuazhIZ25XMStORlUyQm8Ku81SO5hVyeWh1zGlryH3GmJABa1xmlIJ
            F/x4dv29/xjX7pjqOZ3ilcNjsKUwuL1Qd/X/As83S6bkG4/uoZ7S2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T07:29:22Z"
    mac: ENC[AES256_GCM,data:lln4A10oRbiR2jvIqEcwcY+InsmBt7Ej6z/t7OZ4pfi/rAtoGXfFzDZOOcwOmW9Vb3jXhw/E2cI8C8xbl7bGnGL0waTwDBA9Csq9iPT5ehBZuYJCzptzhcThorxtX6BBQzbgeHWovFEwaxTuMsCeLurqBx78+6jvuA8gvGI9jBs=,iv:3x0RwENAn1Ho9xzkexaeYT9nru+vWBu6owIWSVwfysM=,tag:/P+rGCRFwb4HpTfDaUcEhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
