apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-setup-logs-data-stream-role-secrets
    namespace: elastic
stringData:
    roles.yml: ENC[AES256_GCM,data:M9jD6sI7aImfPwK25mfEieIkMqrgSR7Wl+TdAhzL3RW8sH6IOOcDjdAikP3FzxQZOSuSybtGUm1FV70C3nPIYRXrS/78IvhsHNrCjGEHiXtxeKux+coaxTbhXeS1JRjep7rglNTDTO8FwjzjQC9Yf4+n1Cg8swe1aOH5+ulCHUB6+4R2NE7j42N4b7Cfd2o8DDuexbY=,iv:E8/V2FWqAJQ6j9/LAbGbMKSDIHfpkdtF9/eZ80UJJkA=,tag:ZvJfKVM2JRUIKOBVZ/aFhg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1hHUFNlTnhGWXd0Z1NS
            dG9DRlF4RGNZN1YzSk96R0hZakxGMDhhV2lzCmxHclI3MENYWnhjY0ZXSWVOWEUr
            TUd3dDNpUHFFWXYwdHllZEZ3M1RUbWsKLS0tIDNYZWpHMi8rbHRqSVN4b2pHNWNX
            a3pXazgycnFySWRURHFUUGowT0JMUGcKMrfHIIeBB3YmY7yYJApbxzqjXdqQoAZw
            0GzK8ATcRWfAlD7ClXWSRTyPEHEOetomtDVuSovh57hj1VDufrOFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:25:04Z"
    mac: ENC[AES256_GCM,data:nJucvMuLbtJurGET6zSfCxXsdJT4//y4eJQaGLgvZmmSYRZ4JEyMMEehGaCSFKyClpEYwp5zv359+SHFy/rJehN7oZ9mJXzDCr2AdeBHoLN+WPmzs+atThIsVsr19XOprtudHMX2sP/5rIJPQEV0c1N8OcO8FKK3dlMZJ4DS9QQ=,iv:P9cUszsAq20cMXqXiZg1tvGBMvtM10lQYUuM+/P4hIc=,tag:I9Oe05qfDaAuwAmVb9Rupw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-role-secrets
    namespace: elastic
    stringData: null
    roles.yml: |-
        logs_writer:
          cluster:
            - monitor
          indices:
            - names:
                - logs*
              privileges:
                - view_index_metadata
                - 'write'
                - 'create_doc'
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1hHUFNlTnhGWXd0Z1NS
            dG9DRlF4RGNZN1YzSk96R0hZakxGMDhhV2lzCmxHclI3MENYWnhjY0ZXSWVOWEUr
            TUd3dDNpUHFFWXYwdHllZEZ3M1RUbWsKLS0tIDNYZWpHMi8rbHRqSVN4b2pHNWNX
            a3pXazgycnFySWRURHFUUGowT0JMUGcKMrfHIIeBB3YmY7yYJApbxzqjXdqQoAZw
            0GzK8ATcRWfAlD7ClXWSRTyPEHEOetomtDVuSovh57hj1VDufrOFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:25:04Z"
    mac: ENC[AES256_GCM,data:nJucvMuLbtJurGET6zSfCxXsdJT4//y4eJQaGLgvZmmSYRZ4JEyMMEehGaCSFKyClpEYwp5zv359+SHFy/rJehN7oZ9mJXzDCr2AdeBHoLN+WPmzs+atThIsVsr19XOprtudHMX2sP/5rIJPQEV0c1N8OcO8FKK3dlMZJ4DS9QQ=,iv:P9cUszsAq20cMXqXiZg1tvGBMvtM10lQYUuM+/P4hIc=,tag:I9Oe05qfDaAuwAmVb9Rupw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-elastic-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:W/fJQoAORA==,iv:T+B+jWzR69CT288W5dDa8mnVeXdF6uw1o4usRTDCivg=,tag:KN7RGeOxURaQBBzJkX0SUw==,type:str]
    password: ENC[AES256_GCM,data:e/70+qNKB0jKJa5DfY8JcCdkGSsXFG3C,iv:DG13YQWauhvAq7zRQXnFRo989PW/MVy/SAAgbZtJmDY=,tag:nVJ0/kIpT4WXpOQLiQNmZg==,type:str]
    roles: ENC[AES256_GCM,data:7FtUSksP4Y+0,iv:O6rR8rl/oiZA9LERXlg4p0FopDnRNKfEGzR1fSspuMg=,tag:mdg7/QxG8RoGqYvCwoRDuw==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1hHUFNlTnhGWXd0Z1NS
            dG9DRlF4RGNZN1YzSk96R0hZakxGMDhhV2lzCmxHclI3MENYWnhjY0ZXSWVOWEUr
            TUd3dDNpUHFFWXYwdHllZEZ3M1RUbWsKLS0tIDNYZWpHMi8rbHRqSVN4b2pHNWNX
            a3pXazgycnFySWRURHFUUGowT0JMUGcKMrfHIIeBB3YmY7yYJApbxzqjXdqQoAZw
            0GzK8ATcRWfAlD7ClXWSRTyPEHEOetomtDVuSovh57hj1VDufrOFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:25:04Z"
    mac: ENC[AES256_GCM,data:nJucvMuLbtJurGET6zSfCxXsdJT4//y4eJQaGLgvZmmSYRZ4JEyMMEehGaCSFKyClpEYwp5zv359+SHFy/rJehN7oZ9mJXzDCr2AdeBHoLN+WPmzs+atThIsVsr19XOprtudHMX2sP/5rIJPQEV0c1N8OcO8FKK3dlMZJ4DS9QQ=,iv:P9cUszsAq20cMXqXiZg1tvGBMvtM10lQYUuM+/P4hIc=,tag:I9Oe05qfDaAuwAmVb9Rupw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-setup-logs-data-stream-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:sKouXQGFP3Fdos1cjSiCi/sShGcbWw==,iv:msJJ8Q1hCoIA29HfVP7pvtFpzFgyJRR1DecP3pDt75A=,tag:mZ6mBzYNT/3L3NoXJ7lS+w==,type:str]
    password: ENC[AES256_GCM,data:8dyqFug5wTLexXG+BG86d+XxyprHOrHr,iv:NOmtF+QMjcOvpHzlWP5B1kaKnvOoSpLWii9/5ERNPV4=,tag:1pLq4jJMGpEXNkPLoUH0Vw==,type:str]
    roles: ENC[AES256_GCM,data:gyp00CG6GARNzsHnK/7wUg3D92NGSQ==,iv:x69NbLkXj6lLCxAvKq4qTksgOUkWzxie7SV5ZJJAels=,tag:CwwO32ts4AoHXaITAYlyHg==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1hHUFNlTnhGWXd0Z1NS
            dG9DRlF4RGNZN1YzSk96R0hZakxGMDhhV2lzCmxHclI3MENYWnhjY0ZXSWVOWEUr
            TUd3dDNpUHFFWXYwdHllZEZ3M1RUbWsKLS0tIDNYZWpHMi8rbHRqSVN4b2pHNWNX
            a3pXazgycnFySWRURHFUUGowT0JMUGcKMrfHIIeBB3YmY7yYJApbxzqjXdqQoAZw
            0GzK8ATcRWfAlD7ClXWSRTyPEHEOetomtDVuSovh57hj1VDufrOFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:25:04Z"
    mac: ENC[AES256_GCM,data:nJucvMuLbtJurGET6zSfCxXsdJT4//y4eJQaGLgvZmmSYRZ4JEyMMEehGaCSFKyClpEYwp5zv359+SHFy/rJehN7oZ9mJXzDCr2AdeBHoLN+WPmzs+atThIsVsr19XOprtudHMX2sP/5rIJPQEV0c1N8OcO8FKK3dlMZJ4DS9QQ=,iv:P9cUszsAq20cMXqXiZg1tvGBMvtM10lQYUuM+/P4hIc=,tag:I9Oe05qfDaAuwAmVb9Rupw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:jgApZWYcJYyHPHE=,iv:W1PrFExUot3iUYkHPG1VXlONP3QqfwVkEP5PyLPH8jE=,tag:X2cZimCEEE+ah+GgZ7+q5w==,type:str]
    password: ENC[AES256_GCM,data:Pu6HYaIwzryvweJvDzx5OJDl/KGy2STp,iv:y88mjmZhHkQE8TAoP5LTWNi0xe/nWwL/AJBkUI9SZXQ=,tag:+v9UJmTJGIfWWJud+pXJNQ==,type:str]
    roles: ENC[AES256_GCM,data:TJLwaEW+HT/0YwQ=,iv:2IDoJB+hyj9RBbT9YPxnBsFU9kUQ4+BcC8jM0yasC2o=,tag:S5my8kiJu2/sOBKpzUmGcA==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1hHUFNlTnhGWXd0Z1NS
            dG9DRlF4RGNZN1YzSk96R0hZakxGMDhhV2lzCmxHclI3MENYWnhjY0ZXSWVOWEUr
            TUd3dDNpUHFFWXYwdHllZEZ3M1RUbWsKLS0tIDNYZWpHMi8rbHRqSVN4b2pHNWNX
            a3pXazgycnFySWRURHFUUGowT0JMUGcKMrfHIIeBB3YmY7yYJApbxzqjXdqQoAZw
            0GzK8ATcRWfAlD7ClXWSRTyPEHEOetomtDVuSovh57hj1VDufrOFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:25:04Z"
    mac: ENC[AES256_GCM,data:nJucvMuLbtJurGET6zSfCxXsdJT4//y4eJQaGLgvZmmSYRZ4JEyMMEehGaCSFKyClpEYwp5zv359+SHFy/rJehN7oZ9mJXzDCr2AdeBHoLN+WPmzs+atThIsVsr19XOprtudHMX2sP/5rIJPQEV0c1N8OcO8FKK3dlMZJ4DS9QQ=,iv:P9cUszsAq20cMXqXiZg1tvGBMvtM10lQYUuM+/P4hIc=,tag:I9Oe05qfDaAuwAmVb9Rupw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secrets
    namespace: fluentd-system
stringData:
    ELASTICSEARCH_USER: ENC[AES256_GCM,data:OZQ6We/3/0d2PIs=,iv:mvylLCHjpy8bzrSEW6i1H+aFJreOdvavjcj+rcr9j8k=,tag:LcqjbRmfpkP1kh2HlP61fA==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:uS357zd3koo44j/Z0Fma/tzjE6iIONzo,iv:SLIkmPaJsZuoBxhpKpDhsrHDJYpJDWz/AFE4M4klGnw=,tag:cv9XnHXNP6TqHj2cfkVlWw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd1hHUFNlTnhGWXd0Z1NS
            dG9DRlF4RGNZN1YzSk96R0hZakxGMDhhV2lzCmxHclI3MENYWnhjY0ZXSWVOWEUr
            TUd3dDNpUHFFWXYwdHllZEZ3M1RUbWsKLS0tIDNYZWpHMi8rbHRqSVN4b2pHNWNX
            a3pXazgycnFySWRURHFUUGowT0JMUGcKMrfHIIeBB3YmY7yYJApbxzqjXdqQoAZw
            0GzK8ATcRWfAlD7ClXWSRTyPEHEOetomtDVuSovh57hj1VDufrOFrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:25:04Z"
    mac: ENC[AES256_GCM,data:nJucvMuLbtJurGET6zSfCxXsdJT4//y4eJQaGLgvZmmSYRZ4JEyMMEehGaCSFKyClpEYwp5zv359+SHFy/rJehN7oZ9mJXzDCr2AdeBHoLN+WPmzs+atThIsVsr19XOprtudHMX2sP/5rIJPQEV0c1N8OcO8FKK3dlMZJ4DS9QQ=,iv:P9cUszsAq20cMXqXiZg1tvGBMvtM10lQYUuM+/P4hIc=,tag:I9Oe05qfDaAuwAmVb9Rupw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
