apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-role-secrets
    namespace: elastic
    stringData: null
    roles.yml: |-
        logs_writer:
          cluster:
            - monitor
          indices:
            - names:
                - logs*
              privileges:
                - 'write'
                - 'create_doc'
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VG4wOUxaaVJwVHFkQ2hq
            S1hTN3J4ZFVUM08yWC9MYkpBVGJPRENQc0VJCkU0cGRqSkF4SHliTjY1ODYydTd3
            MExUbEJsRm5Cb3FZdkVwYmx6c3phRm8KLS0tICtodzRwKy84ay9lYVBVQVZ4cklS
            VFhWNUYzOW01V1ZYelJsaUwxbGdqd2sK4uXV7irhw7sLp0RfNoUcS7IHr/AZXyfH
            9slcffYwRDYSpr+7v0wJYAcTml1TTlttA5StBaOXBVcFRTIYYp8JOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T02:45:14Z"
    mac: ENC[AES256_GCM,data:Gak5r4ggyv7n/fTkn1hpaz2kxFD/7TxI8BMBvw7aDxdwjKsbXhqJcqv3jIbZRq75BYSSQbdF3Z5X3wpti4STdsj7Wk4I9EA1Gx03IePslIJexyE2Lgn00sJCdtJJ5N1stJkWg0Ff35lRgr1BYaWfMxUJzJjXqc5OzfyN+yCpz14=,iv:GmEQ0mFZADxf612ywthi/Y0rZ/LiGomjFb8t4OKCrrI=,tag:rOz4WNaZj0vYD8g1/Ndn5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-elastic-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:rCi+pY7NyQ==,iv:a52i3Km0rFZoec8FqjjKGqMOgNuZWjSXwJknpLMqqjo=,tag:nr+r3XtgelZhmtg010audg==,type:str]
    password: ENC[AES256_GCM,data:7ZrXfsiobdqbNxS+AEkHsPU3M1SQ7Dfo,iv:cTTaGw1kIRPs0mMVglD4YROdJ0xF1Ye39w/jMIVS1Hw=,tag:gKgO+QXoHAAjNGw0hIJwnQ==,type:str]
    roles: ENC[AES256_GCM,data:6PhQjEHEBU8I,iv:aLwdSBJyktsb79F15j1OO/nfoEf4i+285/rGXCBfFk8=,tag:juPeABjGL0hxANfPBP1JmQ==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VG4wOUxaaVJwVHFkQ2hq
            S1hTN3J4ZFVUM08yWC9MYkpBVGJPRENQc0VJCkU0cGRqSkF4SHliTjY1ODYydTd3
            MExUbEJsRm5Cb3FZdkVwYmx6c3phRm8KLS0tICtodzRwKy84ay9lYVBVQVZ4cklS
            VFhWNUYzOW01V1ZYelJsaUwxbGdqd2sK4uXV7irhw7sLp0RfNoUcS7IHr/AZXyfH
            9slcffYwRDYSpr+7v0wJYAcTml1TTlttA5StBaOXBVcFRTIYYp8JOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T02:45:14Z"
    mac: ENC[AES256_GCM,data:Gak5r4ggyv7n/fTkn1hpaz2kxFD/7TxI8BMBvw7aDxdwjKsbXhqJcqv3jIbZRq75BYSSQbdF3Z5X3wpti4STdsj7Wk4I9EA1Gx03IePslIJexyE2Lgn00sJCdtJJ5N1stJkWg0Ff35lRgr1BYaWfMxUJzJjXqc5OzfyN+yCpz14=,iv:GmEQ0mFZADxf612ywthi/Y0rZ/LiGomjFb8t4OKCrrI=,tag:rOz4WNaZj0vYD8g1/Ndn5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:r5wNKdaooF4ZOeI=,iv:WeBJ0SWLXCajvejEFpuZcAoFAzvZgq/xSni99L9ULNU=,tag:1MBsXRBnWGAuxt+uNOXQtQ==,type:str]
    password: ENC[AES256_GCM,data:JSPdUl6r/CVZSHSjryqXKIVvgdgkNFMe,iv:jSv4KseGfAIrW3Wkm8e7ONMAaO0/l6jM2U/UY3qGApw=,tag:bOXvynSwYvx4hAN74XwisQ==,type:str]
    roles: ENC[AES256_GCM,data:jjSwIGj6oE8qdK8=,iv:bUM8FIOinBRTA0u9YAN86dngYb+xjybDgYn60aMXYPo=,tag:38cZrfeZIXGsXsqyOR/dcQ==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VG4wOUxaaVJwVHFkQ2hq
            S1hTN3J4ZFVUM08yWC9MYkpBVGJPRENQc0VJCkU0cGRqSkF4SHliTjY1ODYydTd3
            MExUbEJsRm5Cb3FZdkVwYmx6c3phRm8KLS0tICtodzRwKy84ay9lYVBVQVZ4cklS
            VFhWNUYzOW01V1ZYelJsaUwxbGdqd2sK4uXV7irhw7sLp0RfNoUcS7IHr/AZXyfH
            9slcffYwRDYSpr+7v0wJYAcTml1TTlttA5StBaOXBVcFRTIYYp8JOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T02:45:14Z"
    mac: ENC[AES256_GCM,data:Gak5r4ggyv7n/fTkn1hpaz2kxFD/7TxI8BMBvw7aDxdwjKsbXhqJcqv3jIbZRq75BYSSQbdF3Z5X3wpti4STdsj7Wk4I9EA1Gx03IePslIJexyE2Lgn00sJCdtJJ5N1stJkWg0Ff35lRgr1BYaWfMxUJzJjXqc5OzfyN+yCpz14=,iv:GmEQ0mFZADxf612ywthi/Y0rZ/LiGomjFb8t4OKCrrI=,tag:rOz4WNaZj0vYD8g1/Ndn5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secrets
    namespace: fluentd-system
stringData:
    ELASTICSEARCH_USER: ENC[AES256_GCM,data:c5tekjnHc6OpC20=,iv:+JDNLsp2XLU7Xceu6gOnAy31lIhDeVkPHPCjC7gWdN8=,tag:nx38VOHz8RSR9o5cfK9DVg==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:pA17N9FIiobdidBG7+VJChCBCAxQbwjb,iv:5JykGEblmA+6d2JlrK1OdhiJIl7IoppN2z86Ui3oqcA=,tag:HjAvKi7DKVJ0Y9yWIAawdg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VG4wOUxaaVJwVHFkQ2hq
            S1hTN3J4ZFVUM08yWC9MYkpBVGJPRENQc0VJCkU0cGRqSkF4SHliTjY1ODYydTd3
            MExUbEJsRm5Cb3FZdkVwYmx6c3phRm8KLS0tICtodzRwKy84ay9lYVBVQVZ4cklS
            VFhWNUYzOW01V1ZYelJsaUwxbGdqd2sK4uXV7irhw7sLp0RfNoUcS7IHr/AZXyfH
            9slcffYwRDYSpr+7v0wJYAcTml1TTlttA5StBaOXBVcFRTIYYp8JOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T02:45:14Z"
    mac: ENC[AES256_GCM,data:Gak5r4ggyv7n/fTkn1hpaz2kxFD/7TxI8BMBvw7aDxdwjKsbXhqJcqv3jIbZRq75BYSSQbdF3Z5X3wpti4STdsj7Wk4I9EA1Gx03IePslIJexyE2Lgn00sJCdtJJ5N1stJkWg0Ff35lRgr1BYaWfMxUJzJjXqc5OzfyN+yCpz14=,iv:GmEQ0mFZADxf612ywthi/Y0rZ/LiGomjFb8t4OKCrrI=,tag:rOz4WNaZj0vYD8g1/Ndn5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
