apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-setup-logs-data-stream-role-secrets
    namespace: elastic
stringData:
    roles.yml: ENC[AES256_GCM,data:uQmpFD4p3DKXf/20m5qPLM3TfYI8XxFhsc4evlhwZBE+kLayDzAsByJk6RnLMTUo/sY3PJadO62vABzQIBAImE4EkVF1RqdXkPYaf3QK/Ni5Eqwv80kOOsFu+4Lqiv8XE+ClqftcC4spGFvM1qZvFSClkXAh+kwu0zzTbM1BpBklWbMcKYDjaJpHbCoi3jYsaujvSPU=,iv:g9Zdqs8UntE//pN1ejlTI5IOcUPmwWUXqAPoBZhCl1w=,tag:2BwZ6fvfoImmQoqFnqtvAQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaakJSbTRlb1N5dVZNMnFp
            TW5MSU1wZC9HcUYzNlh4Rzg1UzFONzV3MWtVCjRkTkphK0tuWXNETjdKUnpNSWE1
            SGN5K1BBSmFDM2lYRWZneHFub1lJMDgKLS0tIERtTUhtSVNLdUlsYktMRm5jOUhv
            SUUwUVVuaUkzTUxINVp2ZzdMbDdEbU0K3lCDuwWeCHmpI2LkFK61T/WaaMN9m2eQ
            BLyuBILL4xqSahY2F7BJce4lGaGldDZXuKqLdkg9sRXD8zVQuMu86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:08:26Z"
    mac: ENC[AES256_GCM,data:CDaXVDuLILx89S3hPhoCQ7UnxxALnY1FAvwwJxlvlXdcIPu/pgq8cLVjA5/vfkbc7cOLwOjjKxTPTZ10m+S6gBM11hku9xir+bWo90UMj91u6Jbn+bMXnTk0jJRVcvGQMLheK8/tjM2adsjs6wecIfgObw1qvfkpN1Th3/jeDJM=,iv:hslVqSabdAGuXmt4aXJeUJ9EuWI1P4UNQ127Ny1NwOs=,tag:aIBtKVMPITpagu08pYU5MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-role-secrets
    namespace: elastic
    stringData: null
    roles.yml: |-
        logs_writer:
          cluster:
            - monitor
          indices:
            - names:
                - logs*
              privileges:
                - 'write'
                - 'create_doc'
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaakJSbTRlb1N5dVZNMnFp
            TW5MSU1wZC9HcUYzNlh4Rzg1UzFONzV3MWtVCjRkTkphK0tuWXNETjdKUnpNSWE1
            SGN5K1BBSmFDM2lYRWZneHFub1lJMDgKLS0tIERtTUhtSVNLdUlsYktMRm5jOUhv
            SUUwUVVuaUkzTUxINVp2ZzdMbDdEbU0K3lCDuwWeCHmpI2LkFK61T/WaaMN9m2eQ
            BLyuBILL4xqSahY2F7BJce4lGaGldDZXuKqLdkg9sRXD8zVQuMu86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:08:26Z"
    mac: ENC[AES256_GCM,data:CDaXVDuLILx89S3hPhoCQ7UnxxALnY1FAvwwJxlvlXdcIPu/pgq8cLVjA5/vfkbc7cOLwOjjKxTPTZ10m+S6gBM11hku9xir+bWo90UMj91u6Jbn+bMXnTk0jJRVcvGQMLheK8/tjM2adsjs6wecIfgObw1qvfkpN1Th3/jeDJM=,iv:hslVqSabdAGuXmt4aXJeUJ9EuWI1P4UNQ127Ny1NwOs=,tag:aIBtKVMPITpagu08pYU5MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-elastic-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:0rM3hqqvKQ==,iv:ik1KBXiNwfpAAY0rwdCYNfZAuO/0cE6koBzBkkXtVyU=,tag:WXN7DBKTyAIIQGDLPC5Srg==,type:str]
    password: ENC[AES256_GCM,data:Hf76IcemPuatbFTAAeJu31LatBdv9mQd,iv:TeU4fFzBMv6co5GLWG2lFPNufoiEgUV649hATqrcs9o=,tag:gTvVqS0QfVl2zXwlNVs5Gg==,type:str]
    roles: ENC[AES256_GCM,data:NYDRs1TOEy5A,iv:YNe8ZvydewjOkmUTzKQz00Mz19V7KZCC4BhAfq2IblY=,tag:Lk9micpyKegT1wV/iWbEGg==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaakJSbTRlb1N5dVZNMnFp
            TW5MSU1wZC9HcUYzNlh4Rzg1UzFONzV3MWtVCjRkTkphK0tuWXNETjdKUnpNSWE1
            SGN5K1BBSmFDM2lYRWZneHFub1lJMDgKLS0tIERtTUhtSVNLdUlsYktMRm5jOUhv
            SUUwUVVuaUkzTUxINVp2ZzdMbDdEbU0K3lCDuwWeCHmpI2LkFK61T/WaaMN9m2eQ
            BLyuBILL4xqSahY2F7BJce4lGaGldDZXuKqLdkg9sRXD8zVQuMu86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:08:26Z"
    mac: ENC[AES256_GCM,data:CDaXVDuLILx89S3hPhoCQ7UnxxALnY1FAvwwJxlvlXdcIPu/pgq8cLVjA5/vfkbc7cOLwOjjKxTPTZ10m+S6gBM11hku9xir+bWo90UMj91u6Jbn+bMXnTk0jJRVcvGQMLheK8/tjM2adsjs6wecIfgObw1qvfkpN1Th3/jeDJM=,iv:hslVqSabdAGuXmt4aXJeUJ9EuWI1P4UNQ127Ny1NwOs=,tag:aIBtKVMPITpagu08pYU5MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-setup-logs-data-stream-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:GnlSj+cu6jxfWf0C4IP2QReiejEXjg==,iv:WQD1QkVsqsl7MgdaeLR22qt40ZPEr7usVomlA0Xly8g=,tag:VXLtPbfr16UYHoGF+t4uVA==,type:str]
    password: ENC[AES256_GCM,data:4hFSc5sz59LjkOzX0RMe53ltxtzL2by2,iv:SenJLJYqcRtqrLW2zODbuG8ZioPwQjGfil7VzjKN5m0=,tag:a9G4gzEKwsAUkL2a1nIGQA==,type:str]
    roles: ENC[AES256_GCM,data:0RBk3HOrTJgZrGN5YLmmtRESQDkiug==,iv:UaSnDjJwQyfpQcf3vBFfmvZNcyyjnn6XgLMOWh6Cz+4=,tag:SMfz7mN6CVpIID+YROqZ0A==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaakJSbTRlb1N5dVZNMnFp
            TW5MSU1wZC9HcUYzNlh4Rzg1UzFONzV3MWtVCjRkTkphK0tuWXNETjdKUnpNSWE1
            SGN5K1BBSmFDM2lYRWZneHFub1lJMDgKLS0tIERtTUhtSVNLdUlsYktMRm5jOUhv
            SUUwUVVuaUkzTUxINVp2ZzdMbDdEbU0K3lCDuwWeCHmpI2LkFK61T/WaaMN9m2eQ
            BLyuBILL4xqSahY2F7BJce4lGaGldDZXuKqLdkg9sRXD8zVQuMu86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:08:26Z"
    mac: ENC[AES256_GCM,data:CDaXVDuLILx89S3hPhoCQ7UnxxALnY1FAvwwJxlvlXdcIPu/pgq8cLVjA5/vfkbc7cOLwOjjKxTPTZ10m+S6gBM11hku9xir+bWo90UMj91u6Jbn+bMXnTk0jJRVcvGQMLheK8/tjM2adsjs6wecIfgObw1qvfkpN1Th3/jeDJM=,iv:hslVqSabdAGuXmt4aXJeUJ9EuWI1P4UNQ127Ny1NwOs=,tag:aIBtKVMPITpagu08pYU5MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-logs-writer-user-secrets
    namespace: elastic
stringData:
    username: ENC[AES256_GCM,data:F9Er/ZUIgTx4zTc=,iv:HRfrK1ocGEIbEz86bjnwm1tQLoCCmCugSpcKzXNZIHY=,tag:qunBqpTpFmuGt/D+e/vCcA==,type:str]
    password: ENC[AES256_GCM,data:+0gN5sPfoK1ZfZwNEUfzla04UaDKbktE,iv:DofJCwxLXp6XZLGRlMrt7Wy9bDbuGtnlG/4IXnY6l1k=,tag:TJneZpXLnEzl5Hck8L/Pmg==,type:str]
    roles: ENC[AES256_GCM,data:OYb+2un/Cw1SIbs=,iv:Gm2dXUGz5c062E0ymSZX0e/tBzwUSR3+366lcm1n2bw=,tag:1H+gXTIKGBksMuKidstbRQ==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaakJSbTRlb1N5dVZNMnFp
            TW5MSU1wZC9HcUYzNlh4Rzg1UzFONzV3MWtVCjRkTkphK0tuWXNETjdKUnpNSWE1
            SGN5K1BBSmFDM2lYRWZneHFub1lJMDgKLS0tIERtTUhtSVNLdUlsYktMRm5jOUhv
            SUUwUVVuaUkzTUxINVp2ZzdMbDdEbU0K3lCDuwWeCHmpI2LkFK61T/WaaMN9m2eQ
            BLyuBILL4xqSahY2F7BJce4lGaGldDZXuKqLdkg9sRXD8zVQuMu86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:08:26Z"
    mac: ENC[AES256_GCM,data:CDaXVDuLILx89S3hPhoCQ7UnxxALnY1FAvwwJxlvlXdcIPu/pgq8cLVjA5/vfkbc7cOLwOjjKxTPTZ10m+S6gBM11hku9xir+bWo90UMj91u6Jbn+bMXnTk0jJRVcvGQMLheK8/tjM2adsjs6wecIfgObw1qvfkpN1Th3/jeDJM=,iv:hslVqSabdAGuXmt4aXJeUJ9EuWI1P4UNQ127Ny1NwOs=,tag:aIBtKVMPITpagu08pYU5MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secrets
    namespace: fluentd-system
stringData:
    ELASTICSEARCH_USER: ENC[AES256_GCM,data:ROSLMHljn5ktppc=,iv:ohDn9u5U5DTNt+0IRTesjuRLEabtaEYACmIo6PS/Jsk=,tag:S+s/1UAxEVaQNGnCT+XfDA==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:UFzpPGxEpjID4t1LXTFnwyy4AQ9+D3up,iv:2MhIyI6pJR+MfIRra+0tvX9vHvPFCOKGBjgQ95tkMi4=,tag:pFzn6PHTYbrN8WM4BYXI8Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wv4al2emm0v09mc0a8zcvphrv5gn6pnt9lf6sr6rrkr5r40juy0qgfp00j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaakJSbTRlb1N5dVZNMnFp
            TW5MSU1wZC9HcUYzNlh4Rzg1UzFONzV3MWtVCjRkTkphK0tuWXNETjdKUnpNSWE1
            SGN5K1BBSmFDM2lYRWZneHFub1lJMDgKLS0tIERtTUhtSVNLdUlsYktMRm5jOUhv
            SUUwUVVuaUkzTUxINVp2ZzdMbDdEbU0K3lCDuwWeCHmpI2LkFK61T/WaaMN9m2eQ
            BLyuBILL4xqSahY2F7BJce4lGaGldDZXuKqLdkg9sRXD8zVQuMu86Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T04:08:26Z"
    mac: ENC[AES256_GCM,data:CDaXVDuLILx89S3hPhoCQ7UnxxALnY1FAvwwJxlvlXdcIPu/pgq8cLVjA5/vfkbc7cOLwOjjKxTPTZ10m+S6gBM11hku9xir+bWo90UMj91u6Jbn+bMXnTk0jJRVcvGQMLheK8/tjM2adsjs6wecIfgObw1qvfkpN1Th3/jeDJM=,iv:hslVqSabdAGuXmt4aXJeUJ9EuWI1P4UNQ127Ny1NwOs=,tag:aIBtKVMPITpagu08pYU5MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
